### ISSUE TITLE
OLD SDK

### ISSUE THREAD

**Issue by nickbash11** [defectly/OpenTalkie#2]
> $ adb install io.github.defectly.opentalkie-Signed.apk 
> Performing Streamed Install
> adb: failed to install Downloads/io.github.defectly.opentalkie-Signed.apk: Failure [INSTALL_FAILED_OLDER_SDK: Failed parse during installPackageLI: /data/app/vmdl1068384816.tmp/base.apk (at Binary XML file line #9): Requires newer sdk version #29 (current version is #28)]
> 

I didn't get quite, I have an older SDK on my phone (android 9) ?

**Comment by defectly** [comment]
> > $ adb install io.github.defectly.opentalkie-Signed.apk
> > Performing Streamed Install
> > adb: failed to install Downloads/io.github.defectly.opentalkie-Signed.apk: Failure [INSTALL_FAILED_OLDER_SDK: Failed parse during installPackageLI: /data/app/vmdl1068384816.tmp/base.apk (at Binary XML file line #9): Requires newer sdk version #29 (current version is #28)]
> 
> I didn't get quite, I have an older SDK on my phone (android 9) ?

it's oriented to android 10...

**Comment by defectly** [comment]
> > $ adb install io.github.defectly.opentalkie-Signed.apk
> > Performing Streamed Install
> > adb: failed to install Downloads/io.github.defectly.opentalkie-Signed.apk: Failure [INSTALL_FAILED_OLDER_SDK: Failed parse during installPackageLI: /data/app/vmdl1068384816.tmp/base.apk (at Binary XML file line #9): Requires newer sdk version #29 (current version is #28)]
> 
> I didn't get quite, I have an older SDK on my phone (android 9) ?

i can set sdk 28 but system audio capture would not work on android 9

**Comment by defectly** [comment]
> > $ adb install io.github.defectly.opentalkie-Signed.apk
> > Performing Streamed Install
> > adb: failed to install Downloads/io.github.defectly.opentalkie-Signed.apk: Failure [INSTALL_FAILED_OLDER_SDK: Failed parse during installPackageLI: /data/app/vmdl1068384816.tmp/base.apk (at Binary XML file line #9): Requires newer sdk version #29 (current version is #28)]
> 
> I didn't get quite, I have an older SDK on my phone (android 9) ?

https://github.com/defectly/OpenTalkie/releases/tag/1.1.0-alpha.4

try install this

**Comment by nickbash11** [comment]
Thank you, it works
